### ISSUE TITLE
Invalid transaction blocks threads in acq/acc

### ISSUE THREAD

**Issue by joefutrelle** [joefutrelle/oii#141]
In the SO post below, someone has a similar issue in Flask, but I believe this is happening in SQLAlchemy based code in the acc/acq workers. What happens is that an invalid transaction that is not rolled back (because of some concurrency issue) prevents further access to the database, until it times out much much later.

http://stackoverflow.com/questions/23301968/invalid-transaction-persisting-across-requests

**Comment by joefutrelle** [comment]
https://groups.google.com/forum/#!topic/sqlalchemy/qAMe78TV0M0

**Comment by joefutrelle** [comment]
Here's a stacktrace:

```
[2016-05-01 14:54:19,300: WARNING/Worker-4] START BATCH IFCB7
[2016-05-01 14:54:19,335: ERROR/MainProcess] Task oii.workflow.async.wakeup[4f5cee9a-d44d-47b8-bb21-f6670278edbf] raised unexpected: StatementError("(sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back",)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 218, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 398, in __protected_call__
    return self.run(*args, **kwargs)
  File "/vagrant/oii/workflow/async.py", line 64, in func_wrapper
    func(*a,**kw)
  File "/vagrant/oii/ifcb2/workflow/batch_acc_worker.py", line 66, in acc_wakeup
    for fs in accession.list_filesets(): # FIXME debug, do all
  File "/vagrant/oii/ifcb2/accession.py", line 114, in list_filesets
    for ddpath in ddpaths:
  File "/vagrant/oii/ifcb2/accession.py", line 95, in get_raw_roots
    ts = self.get_time_series()
  File "/vagrant/oii/ifcb2/accession.py", line 93, in get_time_series
    return self.session.query(TimeSeries).filter(and_(TimeSeries.label==self.ts_label,TimeSeries.enabled)).first()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2469, in first
    ret = list(self[0:1])
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2292, in __getitem__
    return list(res)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2571, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2586, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1078, in _execute_context
    None, None)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1071, in _execute_context
    conn = self._revalidate_connection()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 391, in _revalidate_connection
    "Can't reconnect until invalid "
StatementError: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back [SQL: u'SELECT time_series.id AS time_series_id, time_series.label AS time_series_label, time_series.description AS time_series_description, time_series.enabled AS time_series_enabled, time_series.live AS time_series_live \nFROM time_series \nWHERE time_series.label = %(label_1)s AND time_series.enabled \n LIMIT %(param_1)s'] [parameters: [immutabledict({})]]
```

Could be a missing commit statement in `Accession.add_fileset`?

**Comment by joefutrelle** [comment]
So there are multiple things that can cause this. One is connections timing out before SQLAlchemy recycles them, which leaves them in an invalid state:

https://mofanim.wordpress.com/2013/01/02/sqlalchemy-mysql-has-gone-away/

The other is failure to roll back sessions when errors occur:

https://bugzilla.mozilla.org/show_bug.cgi?id=1016722

**Comment by joefutrelle** [comment]
The timeout thing looks like it may very well be the issue, since the batch accession worker sits idle for extremely long periods of time.

**Comment by joefutrelle** [comment]
The issue is failure to roll back.

The dashboard has this issue too, opening a separate issue for that
