### ISSUE TITLE
IFCB resolver bootstrapping fails under Celery blob worker

### ISSUE THREAD

**Issue by joefutrelle** [joefutrelle/oii#33]
I have successfully run almost exactly the same code before, so I'm not sure why it's failing on the wf_tools branch, but I'm getting this exception in the blob worker trying to call `parse_pid` on a known good pid. The good news is that stack traces are now propagating to the database so I can track worker errors. The bad news is I've got an error to track.

````
Traceback (most recent call last):
  File "/home/ubuntu/dev/oii/workflow/client.py", line 117, in do_all_work
    callback(pid,job)
  File "/home/ubuntu/dev/oii/ifcb2/workflow/blob_worker.py", line 40, in extract_blobs
    parsed_pid = parse_pid(pid)
  File "/home/ubuntu/dev/oii/ifcb2/identifiers.py", line 23, in parse_pid
    return next(get_resolver().ifcb.pid(pid))
  File "/home/ubuntu/dev/oii/utils.py", line 80, in inner
    new_value = fn(*args,**kw)
  File "/home/ubuntu/dev/oii/ifcb2/__init__.py", line 38, in get_resolver
    return ldr.get_resolver(locate_resolver('ifcb.xml'))
  File "/home/ubuntu/dev/oii/ldr.py", line 734, in get_resolver
    return Resolver(locate_resolver(relative_path))
  File "/home/ubuntu/dev/oii/utils.py", line 80, in inner
    new_value = fn(*args,**kw)
  File "/home/ubuntu/dev/oii/ldr.py", line 731, in locate_resolver
    return search_path(relative_path)
  File "/home/ubuntu/dev/oii/utils.py", line 34, in search_path
    cands = [os.path.join(d,pathname_suffix) for d in sys.path]
  File "/usr/lib/python2.7/posixpath.py", line 75, in join
    if b.startswith('/'):
AttributeError: 'NoneType' object has no attribute 'startswith'
````

**Comment by joefutrelle** [comment]
When Celery runs this worker on my test machine it has a different sys.path than if I run python from the command line. Here's the command line:

````
>>> print sys.path
['', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
````

And here's the worker reporting its `sys.path`:

````
[2015-02-10 14:32:08,858: WARNING/MainProcess] celery@blob_worker ready.
[2015-02-10 14:32:15,897: WARNING/Worker-4] ['/usr/bin', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
````

so the bootstrapping strategy is flawed and needs to be extended to support the Celery worker case either through explicit configuration or proper use of the relevant Python configuration utilities.

**Comment by joefutrelle** [comment]
This is fixed by making `oii.ifcb2.resolvers` a module, importing it, and using its `__path__` member.
