### ISSUE TITLE
workflow service mutex stage management broken under wakeup()

### ISSUE THREAD

**Issue by joefutrelle** [joefutrelle/oii#48]
Batch accession is not working. After one job, wakeup fails, giving this message on the client side:

```
[2015-07-27 18:33:27,413: ERROR/MainProcess] Task oii.workflow.async.wakeup[ba007d77-0b8e-4cf3-a3cc-36f7fb87429f] raised unexpected: RuntimeError(u'mutex ifcb:acc:test in unknown state',)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 218, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 398, in __protected_call__
    return self.run(*args, **kwargs)
  File "/vagrant/oii/workflow/async.py", line 64, in func_wrapper
    func(*a,**kw)
  File "/vagrant/oii/ifcb2/workflow/batch_acc_worker.py", line 80, in acc_wakeup
    client.wakeup()
  File "/vagrant/oii/workflow/client.py", line 184, in __exit__
    raise RuntimeError("mutex %s in unknown state" % self.mutex_pid)
RuntimeError: mutex ifcb:acc:test in unknown state
```

This is a concurrency exception in the database. First a commit is attempted on a closed transaction, then key constraint violations start accumulating.

```
[Mon Jul 27 18:33:27.774500 2015] [:error] [pid 1572:tid 140193296103168] [remote 127.0.0.1:19538] InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (psycopg2.IntegrityError) duplicate key value violates unique constraint "products_pkey"
[Mon Jul 27 18:33:27.774507 2015] [:error] [pid 1572:tid 140193296103168] [remote 127.0.0.1:19538] DETAIL:  Key (id)=(15) already exists.
[Mon Jul 27 18:33:27.774511 2015] [:error] [pid 1572:tid 140193296103168] [remote 127.0.0.1:19538]  [SQL: 'INSERT INTO products (id, pid, state, event, message, ts, ttl, expires, priority) VALUES (%(id)s, %(pid)s, %(state)s, %(event)s, %(message)s, %(ts)s, %(ttl)s, %(expires)s, %(priority)s)'] [parameters: {'expires': None, 'pid': u'http://demi.whoi.edu/test/IFCB2_2007_182_021542_raw', 'ts': datetime.datetime(2015, 7, 27, 18, 33, 25, tzinfo=<UTC>), 'event': 'created', 'priority': 100, 'state': 'waiting', 'ttl': None, 'message': None, 'id': 15}]```

**Comment by joefutrelle** [comment]
A workaround that seems to work is changing the number of WSGI threads on the workflow webapp to 1. This is not a fix for the underlying concurrency design flaw, but it does enable batch accession to work.
